[package]
name = "rsrc"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { version = "0.1.0", path = "../common" }
glam = { version = "0.30.9", features = ["serde", "rkyv"] }
gltf = "1.4.1"
rkyv = "0.8.12"
serde = "1.0.228"
walkdir = "2"
